# -*- coding: utf-8 -*-
"""Muñoz_Escobar_Daniel_Arukin_S7CASA_plots

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nwUd7JKE_BRQVS-RqyM3sR3fb22hPPWo
"""

import numpy as np
import matplotlib.pylab as plt
#Sol fijo

#Método de euler 2do orden
datos_euler_2orden_sol_fijo=np.genfromtxt("Posicion de la tierra respecto al sol fijo euler",dtype=None, delimiter='|')

plt.figure()
plt.title('Mov tierra euler 2orden sol fijo', fontsize=12)
plt.plot(datos_euler_2orden_sol_fijo[:,0],datos_euler_2orden_sol_fijo[:,1],'g')
plt.savefig("Mov tierra euler 2orden sol fijo.pdf")

#Método de LeapFrog
datos_LeapFrog_sol_fijo=np.genfromtxt("Posicion de la tierra respecto al sol fijo LeapFrog",dtype=None, delimiter='|')

plt.figure()
plt.title('Mov tierra LeapFrog sol fijo', fontsize=12)
plt.plot(datos_LeapFrog_sol_fijo[:,0],datos_LeapFrog_sol_fijo[:,1],'b')
plt.savefig("Mov tierra LeapFrog sol fijo.pdf")

#sol libre

#Método de euler 2do orden
datos_tierra_euler_2orden_sol_libre=np.genfromtxt("Posicion de la tierra respecto al sol libre euler",dtype=None, delimiter='|')
datos_sol_libre_euler_2orden=np.genfromtxt("Posicion del sol libre euler",dtype=None, delimiter='|')
plt.figure()
plt.title('Mov sol-tierra euler 2orden sol libre', fontsize=12)
plt.plot(datos_tierra_euler_2orden_sol_libre[:,0],datos_tierra_euler_2orden_sol_libre[:,1],'g', datos_sol_libre_euler_2orden[:,0], datos_sol_libre_euler_2orden[:,1],'r')
plt.savefig("Mov sol-tierra euler 2orden sol libre.pdf")

#método de LeapFrog
datos_tierra_LeapFrog_sol_libre=np.genfromtxt("Posicion de la tierra respecto al sol libre LeapFrog",dtype=None, delimiter='|')
datos_sol_libre_LeapFrog=np.genfromtxt("Posicion del sol libre LeapFrog",dtype=None, delimiter='|')
plt.figure()
plt.title('Mov sol-tierra LeapFrog sol libre', fontsize=12)
plt.plot(datos_tierra_LeapFrog_sol_libre[:,0],datos_tierra_LeapFrog_sol_libre[:,1],'b', datos_sol_libre_LeapFrog[:,0], datos_sol_libre_LeapFrog[:,1],'r')
plt.savefig("Mov sol-tierra LeapFrog sol libre.pdf")


#Como podemos ver en ambas gráficas del sol libre, el movimiento del sol (el que está de color rojo) se ve como una línea ya que el movimiento en x que realiza el sol es muy pequeño respecto al movimiento en y del mismo y sobre todo de los movimientos de la tierra, por lo que su movimiento no es casi perceptible.